const categoryToNumberOfPngs = {
    "adventurousFemale": 2,
    "adventurousMale": 2,
    "ambitiousMale": 2,
    "ambitiousFemale": 4,
    "chillMale": 2,
    "chillFemale": 1,
    "compassionateMale": 5,
    "compassionateFemale": 2,
    "confidentMale": 1,
    "confidentFemale": 4,
    "creativeMale": 5,
    "creativeFemale": 2,
    "curiousMale": 1,
    "curiousFemale": 1,
    "energeticMale": 1,
    "energeticFemale": 3,
    "friendlyMale": 3,
    "friendlyFemale": 1,
    "humbleMale": 2,
    "humbleFemale": 1,
    "loyalMale": 2,
    "loyalFemale": 1,
    "optimisticMale": 3,
    "optimisticFemale": 1,
    "outgoingMale": 2,
    "outgoingFemale": 3,
    "quirkyMale": 4,
    "quirkyFemale": 3,
    "spontaneousMale": 2,
    "spontaneousFemale": 3,
    "tech-savvyMale": 4,
    "tech-savvyFemale": 2,
    "wittyFemale": 1,
    "wittyMale" : 1,
  };

  export {categoryToNumberOfPngs}