"use client"

import "./globals.css";
import { IdentityContextProvider } from "./lib/identityContext";

export const metadata = {
  title: "Anon Chat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <IdentityContextProvider>{children}</IdentityContextProvider>
      </body>
    </html>
  );
}
