"use client"

import "./globals.css";
import { PersonalityContextProvider } from "./lib/personalitiesContext";

export const metadata = {
  title: "Anon Chat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <PersonalityContextProvider>{children}</PersonalityContextProvider>
      </body>
    </html>
  );
}
